### PR TITLE
Enable `io.popen` on Linux

### PR DESCRIPTION
**Pull request by jonas-schievink**
Also adds a REPL example so I could test this :)

Basically, this is a port of https://github.com/tomaka/hlua/pull/132.

Now, there's a few more things we could do. `LUA_USE_LINUX` enables a bit more than just `io.popen`, and it should work fine on a few other OSes, but I didn't bother checking where exactly it is supported.

### CODE REVIEW

**Comment by kyren** [comment]
Yeah, not only linux, we really should be defining all of LUA_USE_LINUX, LUA_USE_WINDOWS, LUA_USE_MACOSX, LUA_USE_POSIX correctly at least.  I sort of punted on that when I was setting this up because I just didn't need it at the time.  I can't remember if there are any more realistic platform defines than that, I don't think so?

The repl example is a SUPER good idea, but you can do even better than that, there's an IncompleteStatement error specifically to make repls with, so you can print '>>' like the normal lua repl.

I'm going to merge your pull request soon, but I'm going to wait until I have a free moment to do the changes I mentioned right afterwards.  Internally at chucklefish we have gitlab-ci build servers for our projects on all pc architectures, so I should be able to do the define changes and at least mostly test it on macos / linux / windows without too much headache.

By the way, I'm still kind of a github scrub (gitscrub?), so I'm not too familiar with common workflows.  There's not a way to like.. collaborate on a pull request is there?  I don't know what the proper workflow here is.. I have a set of related changes to your pull request that I would like to make, and I can either 1) make the changes suggested by the pull request then close it, 2) merge it then immediately work on the changes in new commits, or 3) somehow collaborate on it?  It's not terribly important here, I push commits all the damn time anyway, I mostly just don't want to violate some github etiquette I'm not aware of.

By the way thanks for all the great pull requests! 👍

**Comment by Timidger** [comment]
> By the way, I'm still kind of a github scrub (gitscrub?), so I'm not too familiar with common workflows. There's not a way to like.. collaborate on a pull request is there? I don't know what the proper workflow here is.. I have a set of related changes to your pull request that I would like to make, and I can either 1) make the changes suggested by the pull request then close it, 2) merge it then immediately work on the changes in new commits, or 3) somehow collaborate on it? It's not terribly important here, I push commits all the damn time anyway, I mostly just don't want to violate some github etiquette I'm not aware of.

Assuming @jonas-schievink didn't forbit it explicitly, you can push directly to the pr [see here for more details](https://help.github.com/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork/)

**Comment by jonas-schievink** [comment]
@kyren Yeah, you should be able to just push to the branch. I've never used that feature either, though.

**Comment by kyren** [comment]
> Assuming @jonas-schievink didn't forbit it explicitly, you can push directly to the pr see here for more details

Thanks!  I might not do that this time but that's good to know.

**Pull request merged**
