### PR TITLE
Use compiletest to make sure unsafe things do not compile

### PR DESCRIPTION
**Pull request by jonas-schievink**
I only added 2 tests I found in `tests.rs`, it would be nice to gather more. If anyone finds something unsafe that we should test against, please leave a comment.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Oh yeah, Travis fails since this only works on nightly. Give me a second.

**Comment by jonas-schievink** [comment]
UGH. Why isn't there a more elegant and usable solution for compile-fail tests? They're pretty important for all sorts of crates...

**Comment by kyren** [comment]
I ended up working off of what you had and managed to get travis working as of 1426bdbc164f46af3f68c523a4356177377bac6f, I didn't put compiletest_rs in [dev-dependencies] though, but it is optional?

I'm not sure if I have it set up in the most optimal way.

**Comment by jonas-schievink** [comment]
@kyren Very nice! The only issue with making compiletest a regular dependency is that downstream crates can now request the `compiletest_rs` feature to be enabled, too. I don't think that's too big of a deal, though.

Eventually I'll revisit my plans to make compile-fail tests more accessible, probably after https://github.com/rust-lang/cargo/pull/4734 lands or https://github.com/rust-lang/rfcs/pull/2318 is accepted and implemented.

Also closing, since this is implemented now.

**Pull request closed without merging**
