### PR TITLE
Rename a few methods to better match their intention or conventions

### PR DESCRIPTION
**Pull request by jonas-schievink**
The commits should be self-explanatory.

I'm still working on some other breaking changes, so you might want to hold off on releasing a new version for now.

### CODE REVIEW

**Comment by kyren** [comment]
I think I agree with all of them other than set -> insert, but I don't feel super strongly about it.  It doesn't return the old value like map insert, nor should it really.

**Comment by jonas-schievink** [comment]
Yeah, should I remove that commit?

**Comment by kyren** [comment]
Yeah I think so, unless you feel differently?

**Comment by jonas-schievink** [comment]
Nah, I've only included that for consistency with Rust maps. Since the function doesn't return the old value anyways, it doesn't matter too much. I've force-pushed the commit away :)

**Comment by jonas-schievink** [comment]
> I'm still working on some other breaking changes, so you might want to hold off on releasing a new version for now.

Actually, scratch that. What I wanted wasn't as simple as I hoped.

**Comment by kyren** [comment]
> Actually, scratch that. What I wanted wasn't as simple as I hoped.

What was the change you wanted to make, something I can assist you with?

**Comment by jonas-schievink** [comment]
I was confused about the array methods defined on `LuaTable` and would have expected them to act on the sequence part of the table instead of asserting that the table is array-like (a notion that Lua does not have), but the current behaviour makes sense, too.

My initial plan was to replace them by methods acting on that sequence part, effectively making `for_each_array_value` equivalent to `ipairs`, but looking at how the `ToLua` impls for `HashSet` and `BTreeSet` work, the current behaviour makes sense, too.

Actually, let me open an issue about this so we can discuss this further.

**Pull request merged**
